spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/creative
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  error:
    include-message: always
  port: 8080
jwt:
  secret: creative
  expiration: 14400