apiVersion: apps/v1
kind: Deployment
metadata:
  name: creative
  labels:
    app: creative
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creative
  template:
    metadata:
      labels:
        app: creative
    spec:
      containers:
        - name: creative
          image: jefferson023/creative:1.0
          ports:
            - port: 8080
            - containerPort: 8080
          imagePullPolicy: Always
