kind: Service
apiVersion: v1
metadata:
  name: creative
spec:
  selector:
    app: creative
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creative
spec:
  selector:
      matchLabels:
        app: creative
  replicas: 1
  template:
    metadata:
      labels:
        app: creative
    spec:
      containers:
        - name: creative
          image: jefferson023/creative:1.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
